---
apiVersion: v1  
kind: Pod
metadata:
  name: namespace-1-nginx
  namespace: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.21
      ports:
        - containerPort: 80
          protocol: 'TCP'
