---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "test-app"
  template:
    metadata:
      labels:
        app: test-app
        ver: "1.0.0"
    spec:
      containers:
        - name: test-app
          image: shaikkhajaibrahim/testapp:1.0.0
          ports:
            - containerPort: 80
              protocol: "TCP"