---
apiVersion: v1
kind: Service
metadata:
  name: act1-service
spec:
  type: NodePort
  selector:
    app: "jenkins"
  ports:
    - nodePort: 32000
      targetPort: 8080
      port: 8080
      protocol: "TCP"
      