---
apiVersion: v1
kind: Pod
metadata:
  name: labels-demo1
  labels:
    app: web
    env: dev
    ver: "1.0"
    project: dd-ecommerce
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
          protocol: "TCP"