---
apiVersion: v1
kind: Pod
metadata:
  name: labels-demo2
  labels:
    app: web
    env: test
    ver: "1.1"
    project: dd-ecomm
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
          protocol: "TCP"